os:
  - linux
services:
  - docker
language: java
jdk:
  - oraclejdk8
install:
  - mvn package -DskipTests=true
script:
  - docker build -t pascalgrimaud/hello-jhipster:2.23.0 .
  - docker images
  - echo $DOCKER_LOGIN -> $DOCKER_PASSWORD
