version: '2'
services:
    hellojhipster-app:
        image: hellojhipster
        external_links:
            - hellojhipster-postgresql:postgresql
            - hellojhipster-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/HelloJhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    hellojhipster-postgresql:
        extends:
            file: postgresql.yml
            service: hellojhipster-postgresql
    hellojhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hellojhipster-elasticsearch
